import React, { useMemo, useState } from 'react';
import { createRoot } from 'react-dom/client';
import { Activity, ArrowRight, BrainCircuit, CheckCircle2, ChevronRight, Factory, Leaf, Menu, Package, Recycle, Route, Search, Send, ShieldCheck, Truck, Wifi, Zap } from 'lucide-react';
import './styles.css';

const IMG = {
  plastic: 'https://images.unsplash.com/photo-1532996122724-e3c354a0b15b?auto=format&fit=crop&w=1200&q=82',
  glass: 'https://images.unsplash.com/photo-1771153789963-746185524870?auto=format&fit=crop&w=1200&q=82',
  cardboard: 'https://images.unsplash.com/photo-1573376671258-62ee7b68c853?auto=format&fit=crop&w=1200&q=82',
  metal: 'https://images.unsplash.com/photo-1777991642395-84d980dcb733?auto=format&fit=crop&w=1200&q=82',
  ewaste: 'https://images.unsplash.com/photo-1616957348213-3dc21d6b06fb?auto=format&fit=crop&w=1200&q=82',
  pot: 'https://images.unsplash.com/photo-1591178116461-9ce960135e05?auto=format&fit=crop&w=1000&q=82',
  food: 'https://images.unsplash.com/photo-1547592180-85f173990554?auto=format&fit=crop&w=1200&q=82',
  box: 'https://images.unsplash.com/photo-1573376671258-62ee7b68c853?auto=format&fit=crop&w=1000&q=82',
  can: 'https://images.unsplash.com/photo-1777991642395-84d980dcb733?auto=format&fit=crop&w=1000&q=82'
};

const DATA = {
  plastic:{name:'Plastic bottles & containers',short:'Plastic',icon:'🧴',bin:'Dry recyclable',image:IMG.plastic,aliases:['plastic','pet','bottle','bottles','water bottle','cold drink bottle','hdpe','ldpe','pp','wrapper','packet','polythene','polythene bag','plastic bag','milk pouch','shampoo bottle','detergent bottle','container'],process:['Collect in dry stream','AI vision identifies polymer','Sort by type','Wash and shred','Extrude into flakes/pellets'],raw:'recycled plastic feedstock',products:[['Plant pots',IMG.pot],['Storage crates',IMG.plastic],['Outdoor furniture',IMG.plastic],['Packaging',IMG.box]],impact:'Clean, separated plastic can re-enter manufacturing instead of becoming mixed waste.'},
  paper:{name:'Paper & newspapers',short:'Paper',icon:'📰',bin:'Paper',image:IMG.cardboard,aliases:['paper','newspaper','news paper','magazine','notebook','book','office paper','copy paper','worksheet','paper sheet','paper bag'],process:['Collect dry paper','AI checks contamination','Grade by fibre','Pulp with water','Press, dry & roll'],raw:'recovered paper fibre',products:[['Notebook paper',IMG.cardboard],['Paper bags',IMG.cardboard],['Packaging sheets',IMG.box],['Tissue products',IMG.cardboard]],impact:'Dry paper can be recovered into new fibre when it is kept away from wet and food waste.'},
  cardboard:{name:'Corrugated cardboard',short:'Cardboard',icon:'📦',bin:'Paper',image:IMG.cardboard,aliases:['cardboard','carton','box','shipping box','delivery box','corrugated box','ecommerce box','packing box'],process:['Collect & flatten','AI checks fibre quality','Remove tape / contaminants','Pulp and refine','Press into board'],raw:'recycled paperboard',products:[['Shipping boxes',IMG.box],['Desk organisers',IMG.box],['Packaging inserts',IMG.box],['Display boards',IMG.cardboard]],impact:'Cardboard fibre can be recovered multiple times when kept clean and dry.'},
  glass:{name:'Glass bottles & jars',short:'Glass',icon:'🍾',bin:'Glass',image:IMG.glass,aliases:['glass','bottle','glass bottle','jar','glass jar','beverage bottle','pickle jar','sauce jar'],process:['Collect glass stream','AI / optical colour sort','Crush into cullet','Clean and remove contaminants','Melt and form'],raw:'clean glass cullet',products:[['New glass bottles',IMG.glass],['Glass jars',IMG.glass],['Tiles',IMG.glass],['Decor pieces',IMG.glass]],impact:'Glass can return to the glass-making process as cullet when it is correctly separated.'},
  metal:{name:'Metal & aluminium cans',short:'Metal',icon:'🥫',bin:'Metal',image:IMG.metal,aliases:['metal','aluminium','aluminum','can','cans','tin can','steel can','metal can','foil','scrap metal','copper'],process:['Collect metal stream','AI + sensor separation','Compact and bale','Melt in controlled plant','Cast new stock'],raw:'recovered metal stock',products:[['New cans',IMG.can],['Sheet metal',IMG.metal],['Utility parts',IMG.metal],['Bike components',IMG.metal]],impact:'Metal recovery keeps valuable material in the manufacturing loop and reduces demand for new raw material.'},
  organic:{name:'Food & garden waste',short:'Organic',icon:'🍎',bin:'Organic',image:IMG.food,aliases:['food','food waste','organic','organic waste','kitchen waste','fruit peel','vegetable peel','peels','leftovers','garden waste','leaves','grass','compost'],process:['Separate at source','AI checks organic stream','Remove contamination','Controlled composting','Cure and screen'],raw:'finished compost',products:[['Garden compost',IMG.food],['Soil conditioner',IMG.food],['Community garden mix',IMG.food],['Compost blend',IMG.food]],impact:'Organic material can return nutrients to soil through managed composting rather than mixed disposal.'},
  ewaste:{name:'Electronic waste',short:'E-waste',icon:'💻',bin:'Special e-waste stream',image:IMG.ewaste,aliases:['e waste','e-waste','ewaste','phone','mobile','smartphone','laptop','computer','keyboard','mouse','charger','cable','earphones','electronics','electronic waste','printer'],process:['Send to authorised e-waste stream','AI identifies device category','Manual / controlled dismantling','Material recovery','Refine recovered metals and plastics'],raw:'recovered electronic materials',products:[['Recovered metal fractions',IMG.ewaste],['Reclaimed plastic feedstock',IMG.ewaste],['Refurbished device parts',IMG.ewaste],['Recovered components',IMG.ewaste]],impact:'E-waste needs a specialised collection route so useful materials can be recovered safely.'},
  textile:{name:'Textiles & old clothes',short:'Textile',icon:'👕',bin:'Textile recovery',image:IMG.plastic,aliases:['textile','cloth','clothes','old clothes','shirt','jeans','fabric','garment','uniform','bedsheet','cotton'],process:['Collect separately','Sort by fibre','Grade for reuse or recycling','Shred / fibre recovery','Spin or form new material'],raw:'recovered textile fibre',products:[['Cleaning cloths',IMG.plastic],['Insulation fibre',IMG.plastic],['New yarn',IMG.plastic],['Upcycled products',IMG.plastic]],impact:'Textiles can be reused first or processed into secondary fibre where suitable.'},
  wood:{name:'Wood & garden trimmings',short:'Wood',icon:'🪵',bin:'Green / bulky stream',image:IMG.food,aliases:['wood','wood waste','branch','branches','tree trimmings','sawdust','timber','wooden pallet','pallet'],process:['Collect bulky / green stream','Sort by clean wood grade','Chip or shred','Screen material','Make boards or biomass feedstock'],raw:'wood fibre / chips',products:[['Particle board feedstock',IMG.box],['Mulch',IMG.food],['Compost carbon mix',IMG.food],['Biomass feedstock',IMG.food]],impact:'Clean wood can be recovered as fibre, mulch or other controlled secondary feedstock.'},
  tyre:{name:'Used tyres',short:'Tyres',icon:'🛞',bin:'Special recovery stream',image:IMG.plastic,aliases:['tyre','tyres','tire','tires','rubber tyre','rubber'],process:['Collect at authorised point','Inspect and sort','Shred mechanically','Separate steel and fibre','Recover rubber granules'],raw:'recovered rubber granules',products:[['Rubber flooring',IMG.plastic],['Playground surfacing',IMG.plastic],['Mats',IMG.plastic],['Rubberised products',IMG.plastic]],impact:'Tyres require a specialised recovery route; recovered rubber can become secondary material.'},
  tetrapak:{name:'Tetra Pak & drink cartons',short:'Drink cartons',icon:'🧃',bin:'Dry recyclable',image:IMG.cardboard,aliases:['tetra pak','tetrapak','drink carton','juice carton','milk carton','beverage carton','carton pack'],process:['Collect dry cartons','Sort by AI stream','Open / bale cartons','Separate fibre and polymer-aluminium fractions','Recover usable material'],raw:'recovered carton fibre',products:[['Paperboard products',IMG.box],['Packaging board',IMG.cardboard],['Recovered polymer-aluminium',IMG.plastic],['Composite boards',IMG.box]],impact:'Drink cartons contain multiple layers, so they need the appropriate recycling route rather than ordinary paper treatment.'}
};

const bins=[['B-104','Residential',82,'Plastic'],['B-218','Market',94,'Organic'],['B-331','Commercial',76,'Cardboard'],['B-409','Food District',91,'Organic'],['B-517','Campus',67,'Paper']];
const allTypes=Object.keys(DATA);

function normal(s){return s.toLowerCase().replace(/[^a-z0-9\s-]/g,' ').replace(/\s+/g,' ').trim();}
function scoreType(q,k){const z=normal(q),d=DATA[k];let score=0;for(const a of d.aliases){const aa=normal(a);if(z===aa) score+=20;if(z.includes(aa)) score+=8;const parts=aa.split(' ');if(parts.length>1&&parts.every(p=>z.includes(p)))score+=5;}return score;}
function detectTypes(q){
  const z=normal(q);
  const hits=allTypes.map(k=>({k,score:scoreType(z,k)})).filter(x=>x.score>0).sort((a,b)=>b.score-a.score);
  if(hits.length) return hits.slice(0,6).map(x=>x.k);
  return [];
}

function App(){
 const [page,setPage]=useState('home'),[menu,setMenu]=useState(false),[material,setMaterial]=useState('plastic'),[query,setQuery]=useState(''),[answer,setAnswer]=useState([]),[buildStep,setBuildStep]=useState(0),[product,setProduct]=useState(DATA.plastic.products[0][0]),[toast,setToast]=useState('');
 const go=p=>{setPage(p);setMenu(false);window.scrollTo({top:0,behavior:'smooth'});};
 const notify=t=>{setToast(t);setTimeout(()=>setToast(''),2400)};
 const chooseMaterial=k=>{setMaterial(k);setBuildStep(0);setProduct(DATA[k].products[0][0]);};
 const ask=(text=query)=>{const q=String(text||'').trim();if(!q)return;let keys=detectTypes(q);if(!keys.length){keys=['plastic'];}setAnswer(keys.map(k=>({k,x:DATA[k]})));setMaterial(keys[0]);setBuildStep(0);setProduct(DATA[keys[0]].products[0][0]);setQuery('');setPage('ai');};
 const d=DATA[material];
 return <div className="app">
  <header><button className="brand" onClick={()=>go('home')}><span>♻</span><b>ECO</b>GRID<small>SMART SOLID WASTE · AI + IoT</small></button><nav className={menu?'open':''}>{[['home','Command Center'],['ai','EcoAI Search'],['recycle','Recycling Lab'],['product','Product Studio'],['iot','IoT City']].map(([id,t])=><button className={page===id?'active':''} onClick={()=>go(id)} key={id}>{t}</button>)}</nav><div className="headerRight"><span className="live"><i/> SYSTEM LIVE</span><button className="menu" onClick={()=>setMenu(!menu)}><Menu/></button></div></header>
  {page==='home'&&<Home go={go} choose={chooseMaterial}/>} 
  {page==='ai'&&<AI query={query} setQuery={setQuery} ask={ask} answer={answer} go={go} choose={chooseMaterial}/>} 
  {page==='recycle'&&<RecycleLab material={material} choose={chooseMaterial} go={go}/>} 
  {page==='product'&&<ProductStudio material={material} choose={chooseMaterial} product={product} setProduct={setProduct} step={buildStep} setStep={setBuildStep} notify={notify}/>} 
  {page==='iot'&&<IoTCity notify={notify}/>} 
  <footer><b>♻ ECOGRID</b><span>Smart Solid Waste Management using AI, IoT & Automation</span><span>Demo intelligence • real-world image references • no API key</span></footer>
  {toast&&<div className="toast">✓ {toast}</div>}
 </div>
}

function Home({go,choose}){return <main>
 <section className="hero"><div className="heroCopy"><div className="eyebrow"><span>●</span> SMART SOLID WASTE MANAGEMENT · AI + IoT</div><h1>See the waste.<br/><em>Understand the system.</em></h1><p>EcoGrid connects smart-bin sensing, AI material recognition, collection routing, recovery plants and circular products in one interactive command center.</p><div className="heroActions"><button className="primary" onClick={()=>go('ai')}><BrainCircuit/> Ask EcoAI <ArrowRight/></button><button className="secondary" onClick={()=>go('recycle')}><Recycle/> Explore real waste streams</button></div><div className="heroStats"><div><b>11</b><span>waste streams</span></div><div><b>50+</b><span>search aliases</span></div><div><b>4</b><span>connected layers</span></div></div></div><CityVisual go={go}/></section>
 <section className="section"><div className="sectionHead"><div><span className="eyebrow">REAL-WORLD MATERIALS</span><h2>Search by the thing <em>in your hand.</em></h2></div><p>Try “plastic bottle + newspaper + old phone” in one query. EcoAI can return multiple waste streams instead of forcing one category.</p></div><div className="photoStreamGrid">{Object.entries(DATA).slice(0,8).map(([k,x])=><button className="photoStream" onClick={()=>{choose(k);go('recycle')}} key={k}><img src={x.image} alt={x.name}/><div><span>{x.icon}</span><b>{x.name}</b><small>{x.bin}</small></div></button>)}</div></section>
 <section className="pipeline"><div className="pipelineIntro"><span className="eyebrow">THE ECOGRID LOOP</span><h2>Sense → understand → <em>recover → create.</em></h2><p>The website is built around the actual AI + IoT workflow: sensors monitor collection demand while AI helps identify and route material streams.</p></div><div className="loop">{[['01','SENSE','IoT fill-level data'],['02','UNDERSTAND','AI material recognition'],['03','COLLECT','Demand-based routing'],['04','RECOVER','Sorting + processing'],['05','CREATE','Circular products']].map((x,i)=><div className="loopNode" key={x[0]}><span>{x[0]}</span><b>{x[1]}</b><small>{x[2]}</small>{i<4&&<ChevronRight/>}</div>)}</div></section>
 <section className="section modules"><span className="eyebrow">SYSTEM MODULES</span><h2>Explore the complete idea</h2><div className="moduleGrid"><Module icon={<BrainCircuit/>} title="EcoAI Search" text="Recognise many everyday waste items in one query and show their next step." go={()=>go('ai')}/><Module icon={<Recycle/>} title="Recycling Lab" text="See the material journey from collection to recovered feedstock." go={()=>go('recycle')}/><Module icon={<Package/>} title="Product Studio" text="Select recovered material and move it through visible manufacturing stages." go={()=>go('product')}/><Module icon={<Wifi/>} title="IoT City" text="Monitor smart-bin levels, alerts and a demand-based collection route." go={()=>go('iot')}/></div></section>
 </main>}

function CityVisual({go}){return <div className="cityVisual"><div className="skyGlow"/><div className="cityTitle"><small>LIVE CITY OPERATIONS</small><b>EcoGrid Network</b></div><div className="buildings">{[1,2,3,4,5,6,7].map(i=><i style={{height:30+i*12}} key={i}/>)}</div><div className="road r1"/><div className="road r2"/><div className="river"/><div className="tree t1">🌳</div><div className="tree t2">🌲</div>{bins.slice(0,4).map((b,i)=><div className="binPin" style={{left:(15+i*22)+'%',top:(27+(i%2)*39)+'%'}} key={b[0]}>♻<b>{b[2]}%</b></div>)}<div className="truckAnim">🚛</div><div className="mapCard"><small>CITY HEALTH</small><b>92%</b><span><i/> AI + IoT channels normal</span></div><button className="mapButton" onClick={()=>go('iot')}>Open operations <ArrowRight/></button></div>}
function Module({icon,title,text,go}){return <button className="module" onClick={go}><span>{icon}</span><b>{title}</b><p>{text}</p><strong>Open module <ArrowRight/></strong></button>}

function AI({query,setQuery,ask,answer,go,choose}){
 const examples=['plastic bottle + newspaper + old phone','cardboard box and glass jar','food waste + garden leaves','aluminium can + plastic bag'];
 const results=answer;
 return <main className="page"><div className="pageHero"><span className="eyebrow">ECOAI · MULTI-ITEM MATERIAL SEARCH</span><h1>Type normal words.<br/><em>EcoAI finds the waste streams.</em></h1><p>Try several things together. The demo engine matches synonyms, product names and common household phrases across 11 waste streams.</p></div>
 <div className="aiSearchHero"><div className="searchBox big"><Search/><input autoFocus value={query} onChange={e=>setQuery(e.target.value)} onKeyDown={e=>e.key==='Enter'&&ask()} placeholder="e.g. plastic bottle, newspaper, old phone, food peel..."/><button onClick={()=>ask()}><Send/> Analyse</button></div><div className="suggestions">{examples.map(x=><button onClick={()=>ask(x)} key={x}>{x}</button>)}</div></div>
 {results.length?<section className="aiResults"><div className="resultHeader"><div><span className="eyebrow">AI MATERIAL REPORT</span><h2>{results.length} stream{results.length>1?'s':''} detected</h2></div><button className="secondary" onClick={()=>setQuery('')}>New search</button></div><div className="resultGrid">{results.map(({k,x})=><article className="resultCard" key={k}><img src={x.image} alt={x.name}/><div className="resultBody"><div className="resultTitle"><span>{x.icon}</span><div><b>{x.name}</b><small>{x.bin}</small></div></div><p>{x.impact}</p><div className="miniJourney">{x.process.slice(0,4).map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><b>{s}</b></div>)}</div><div className="productChips"><small>REAL-WORLD PRODUCT OUTCOMES</small>{x.products.slice(0,4).map(([p,img])=><button onClick={()=>{choose(k);go('product')}} key={p}><img src={img} alt=""/><span>{p}</span></button>)}</div><button className="primary full" onClick={()=>{choose(k);go('recycle')}}>Open {x.short} recycling journey <ArrowRight/></button></div></article>)}</div></section>:<section className="aiEmpty"><BrainCircuit/><h2>Ask EcoAI anything about everyday solid waste</h2><p>Examples: “what can I do with an old laptop?”, “plastic bottle + glass jar”, “cardboard box”, or “food scraps and leaves”.</p></section>}
 <section className="section compact"><div className="sectionHead"><div><span className="eyebrow">KNOWLEDGE BASE</span><h2>11 waste streams. <em>One search.</em></h2></div></div><div className="knowledgeGrid">{Object.entries(DATA).map(([k,x])=><button className="knowledgeCard" onClick={()=>{choose(k);go('recycle')}} key={k}><img src={x.image} alt={x.name}/><div><span>{x.icon}</span><b>{x.short}</b><small>{x.aliases.slice(0,3).join(' · ')}</small></div></button>)}</div></section>
 </main>}

function RecycleLab({material,choose,go}){const x=DATA[material];return <main className="page"><div className="pageHero"><span className="eyebrow">RECYCLING LAB · REAL MATERIAL JOURNEY</span><h1>Waste in.<br/><em>Recovered material out.</em></h1><p>Each stream has its own sorting and recovery path. The flow below is a simulation of the process, not a claim of a specific local plant.</p></div><div className="materialTabs">{Object.entries(DATA).map(([k,x])=><button className={k===material?'active':''} onClick={()=>choose(k)} key={k}>{x.icon} {x.short}</button>)}</div><div className="labHero"><img src={x.image} alt={x.name}/><div><span className="eyebrow">SELECTED STREAM</span><h2>{x.name}</h2><p>{x.impact}</p><div className="tagRow"><span>INPUT · {x.bin}</span><span>OUTPUT · {x.raw}</span></div></div></div><div className="labGrid"><section className="labMachine"><div className="machineHeader"><span>SIMULATED MATERIAL LINE</span><b>{x.name}</b></div><div className="factoryVisual"><div className="belt"/><div className="wastePiece">{x.icon}</div>{x.process.slice(0,3).map((s,i)=><div className={'machineBox m'+(i+1)} key={s}><Recycle/><b>{i===0?'AI SORT':i===1?'PROCESS':'RECOVER'}</b><small>{s}</small></div>)}<div className="outputPiece">♻<b>{x.raw}</b></div></div><div className="labFooter"><span>INPUT <b>{x.name}</b></span><ArrowRight/><span>OUTPUT <b>{x.raw}</b></span></div></section><aside className="labSteps"><span className="eyebrow">PROCESS TRACE</span>{x.process.map((s,i)=><div className="labStep" key={s}><span>{String(i+1).padStart(2,'0')}</span><div><b>{s}</b><small>{i===0?'Material enters the correct stream.':i===x.process.length-1?'Recovered feedstock is ready for manufacturing.':'The stream is separated, cleaned or transformed for the next stage.'}</small></div><CheckCircle2/></div>)}<button className="primary full" onClick={()=>go('product')}>Use {x.raw} in Product Studio <ArrowRight/></button></aside></div><div className="productPreview"><div><span className="eyebrow">PRODUCT POSSIBILITIES</span><h2>Recovered material → <em>useful products.</em></h2></div><div className="previewItems">{x.products.map(([p,img])=><button key={p} onClick={()=>go('product')}><img src={img} alt={p}/><b>{p}</b></button>)}</div></div></main>}

function ProductStudio({material,choose,product,setProduct,step,setStep,notify}){const x=DATA[material];const done=step>=x.process.length;const chosen=x.products.find(p=>p[0]===product)||x.products[0];return <main className="page"><div className="pageHero"><span className="eyebrow">PRODUCT STUDIO · CIRCULAR MANUFACTURING</span><h1>Choose the output.<br/><em>Watch the factory line.</em></h1><p>This is the “what happens next?” part: recovered material becomes a visible product outcome.</p></div><div className="studioGrid"><section className="productCanvas"><div className="canvasTop"><span>FACTORY SIMULATION</span><span>LINE 04 · ACTIVE</span></div><div className="factoryLine"><div className="feedMaterial"><img src={x.image} alt=""/><small>RECOVERED MATERIAL</small><b>{x.raw}</b></div><ArrowRight/><div className="reactor"><div className="spin">⚙</div><b>REPROCESSOR</b><small>{step===0?'Waiting for start':step<x.process.length?x.process[step]:'Manufacturing complete'}</small></div><ArrowRight/><div className={'finished '+(done?'done':'')}><img src={chosen[1]} alt={chosen[0]}/><small>FINAL PRODUCT</small><b>{product}</b>{done&&<em>✓ CREATED</em>}</div></div><div className="progress"><div style={{width:Math.min(100,(step/x.process.length)*100)+'%'}}/></div><div className="stageLabels">{x.process.map((s,i)=><span className={i<step?'done':i===step?'current':''} key={s}>{i+1}. {s}</span>)}</div></section><aside className="studioControls"><label>01 · RECOVERED MATERIAL</label><div className="selectGrid">{Object.entries(DATA).map(([k,x])=><button className={k===material?'active':''} onClick={()=>choose(k)} key={k}><img src={x.image} alt=""/><span>{x.short}</span></button>)}</div><label>02 · FINAL PRODUCT</label><div className="productSelect">{x.products.map(([p,img])=><button className={p===product?'active':''} onClick={()=>setProduct(p)} key={p}><span><img src={img} alt=""/>{p}</span><ChevronRight/></button>)}</div><label>03 · RUN FACTORY</label><button className="primary full" onClick={()=>{if(step<x.process.length)setStep(step+1);else notify(product+' created from '+x.raw+'!')}}>{step<x.process.length?'Run next manufacturing stage →':'✓ Product complete — create another'}</button><div className="xpBox"><Zap/><div><b>{step}/{x.process.length}</b><small>stages complete</small></div></div></aside></div></main>}

function IoTCity({notify}){return <main className="page"><div className="pageHero"><span className="eyebrow">IOT CITY · SENSORS + COLLECTION</span><h1>The city <em>responds to demand.</em></h1><p>Smart bins provide fill-level telemetry, while the operations layer prioritises collection instead of treating every route as identical.</p></div><div className="iotGrid"><section className="iotMap"><div className="iotRoad a"/><div className="iotRoad b"/><div className="iotRoad c"/><div className="iotRiver"/>{bins.map((b,i)=><button className={'iotBin '+(b[2]>85?'alert':'')} style={{left:(10+i*18)+'%',top:(20+(i%3)*25)+'%'}} onClick={()=>notify('Dispatch priority updated for '+b[0])} key={b[0]}><span>♻</span><b>{b[0]}</b><small>{b[2]}% full</small></button>)}<div className="routeTruck">🚛</div><div className="iotLegend"><span><i className="green"/> Normal</span><span><i className="red"/> Priority</span><span><i className="blue"/> Route</span></div></section><aside className="alerts"><div className="alertHead"><span className="eyebrow">LIVE ALERTS</span><b>5 smart bins reporting</b></div>{bins.map(b=><div className="alertRow" key={b[0]}><span className={b[2]>85?'hotDot':''}>●</span><div><b>{b[0]} · {b[1]}</b><small>{b[3]} stream · threshold 80%</small></div><strong>{b[2]}%</strong></div>)}<button className="primary full" onClick={()=>notify('AI route prioritised the highest-fill bins first')}>Optimise collection route <Route/></button></aside></div><div className="iotCards"><div><Wifi/><b>IoT sensing</b><p>Fill-level telemetry is the city input layer.</p></div><div><BrainCircuit/><b>AI classification</b><p>Vision models can classify multiple waste categories in sorting workflows.</p></div><div><Truck/><b>Fleet response</b><p>Only bins requiring service enter the priority route.</p></div><div><ShieldCheck/><b>Safer streams</b><p>Special streams such as e-waste can be separated earlier.</p></div></div></main>}

createRoot(document.getElementById('root')).render(<App/>);
